# Generated by Django 3.0.5 on 2020-05-06 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200428_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Rating star', 'verbose_name_plural': 'Rating stars'},
        ),
    ]
